name: Run Pytest

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: python:3.11

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install

    - name: Run tests with pytest
      run: poetry run pytest tests/
